### ISSUE TITLE
Python 3.5: _pickle.PicklingError

### ISSUE THREAD

**Issue by karel-brinda** [karel-brinda/smbl#31]
**Example**

``` python
import smbl

rule:
    input:
        smbl.prog.SAMTOOLS

include: smbl.include()
```

**Error**

```
Provided cores: 4
Rules claiming more threads will be scaled down.
Job counts:
    count   jobs
    1   1
    1   30
    2
rule 30:
    output: /Users/karel/.smbl/bin/samtools
Traceback (most recent call last):
  File "/Users/karel/anaconda/lib/python3.5/multiprocessing/queues.py", line 241, in _feed
    obj = ForkingPickler.dumps(obj)
  File "/Users/karel/anaconda/lib/python3.5/multiprocessing/reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function __rule_2 at 0x10394a840>: it's not the same object as snakemake.workflow.__rule_2
```

**Associated discussion**

https://bitbucket.org/snakemake/snakemake/issues/257/_picklepicklingerror

**Comment by karel-brinda** [comment]
Observation: metagenomic simulation - generating *.fai files ok
